In [84]:
import numpy as np
import random
    
tic = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print (tic)

status = "\nKeep Going\n"

while status == "\nKeep Going\n":
    x = int(input("\nPlayer 1, pick your square\n"))
    tic = np.where (tic==[x],0,tic)
    print ("\n",tic)
    if [0,0,0] in tic.tolist():
        status = "\nPlayer 1 has Won\n"
    elif sum(tic[ : ,0]) == 0 or sum(tic[ : ,1]) == 0 or sum(tic[ : ,2]) == 0:
        status = "\nPlayer 1 has Won\n"
    elif sum([tic[0,0],tic[1,1],tic[2,2]]) == 0 or sum([tic[0,2],tic[1,1],tic[2,0]]) == 0:
        status = "\nPlayer 1 has Won\n"
    print (status)
    if status == "\nPlayer 1 has Won\n":
        break
    y = int(input("\nPlayer 2, pick your square\n"))
    tic = np.where (tic==[y],99,tic)
    print ("\n",tic)
    if [99,99,99] in tic.tolist():
        status = "\nPlayer 2 has Won\n"
    elif sum(tic[ : ,0]) == 297 or sum(tic[ : ,1]) == 297 or sum(tic[ : ,2]) == 297:
        status = "\nPlayer 2 has Won\n"
    elif sum([tic[0,0],tic[1,1],tic[2,2]]) == 297 or sum([tic[0,2],tic[1,1],tic[2,0]]) == 297:
        status = "\nPlayer 2 has Won\n"
    print (status)   
   




[[1 2 3]
 [4 5 6]
 [7 8 9]]

Player 1, pick your square
1

 [[0 2 3]
 [4 5 6]
 [7 8 9]]

Keep Going


Player 2, pick your square
2

 [[ 0 99  3]
 [ 4  5  6]
 [ 7  8  9]]

Keep Going


Player 1, pick your square
6

 [[ 0 99  3]
 [ 4  5  0]
 [ 7  8  9]]

Keep Going


Player 2, pick your square
5

 [[ 0 99  3]
 [ 4 99  0]
 [ 7  8  9]]

Keep Going


Player 1, pick your square
7

 [[ 0 99  3]
 [ 4 99  0]
 [ 0  8  9]]

Keep Going


Player 2, pick your square
8

 [[ 0 99  3]
 [ 4 99  0]
 [ 0 99  9]]

Player 2 has Won



In [172]:
import numpy as np
    
tic = np.array([["1","2","3"], ["4","5","6"], ["7","8","9"]])

print ("\033[4m",('|'.join(map(str, tic[0]))),"\033[0m")
print ("\033[4m",('|'.join(map(str, tic[1]))),"\033[0m")
print ("\033[4m",('|'.join(map(str, tic[2]))),"\033[0m")

status = "\nKeep Going\n"

while status == "\nKeep Going\n":
    
        
    x = str(input("\nX, pick your square\n"))
    if x in tic and x != "O":
        tic = np.where (tic==[x],"X",tic)
        print ("\n")
        print ("\033[4m",('|'.join(map(str, tic[0]))),"\033[0m")
        print ("\033[4m",('|'.join(map(str, tic[1]))),"\033[0m")
        print ("\033[4m",('|'.join(map(str, tic[2]))),"\033[0m")
        if ["X","X","X"] in tic.tolist():
            status = "\nX has Won\n"
        elif tic[0,0] == tic[1,1] == tic[2,2] or tic[0,2] == tic[1,1] == tic[2,0] or tic[0,0] == tic[1,0] == tic[2,0] or tic[0,1] == tic[1,1] == tic[2,1] or tic[0,2] == tic[1,2] == tic[2,2]:
            status = "\n X has Won\n"
        print (status)
    else:
        print ("Please choose from available squares")
        continue
    if (np.count_nonzero(tic == "X")) + (np.count_nonzero(tic == "O")) == 9 and status == "\nKeep Going\n":
        status = "It's a draw"
        print (status)
    
    if status != "\nKeep Going\n":
        break
    
    
        
    success = "no"
    while success == "no":
        o = str(input("\nO, pick your square\n"))
        if o in tic and o != "X":
            tic = np.where (tic==[o],"O",tic)
            print ("\n")
            print ("\033[4m",('|'.join(map(str, tic[0]))),"\033[0m")
            print ("\033[4m",('|'.join(map(str, tic[1]))),"\033[0m")
            print ("\033[4m",('|'.join(map(str, tic[2]))),"\033[0m")
            if ["O","O","O"] in tic.tolist():
                status = "\nO has Won\n"
            elif tic[0,0] == tic[1,1] == tic[2,2] or tic[0,2] == tic[1,1] == tic[2,0] or tic[0,0] == tic[1,0] == tic[2,0] or tic[0,1] == tic[1,1] == tic[2,1] or tic[0,2] == tic[1,2] == tic[2,2]:
                status = "\n O has Won\n"
            print (status)
            success = "yes"
        else:
            print ("Please choose from available squares")
        if (np.count_nonzero(tic == "X")) + (np.count_nonzero(tic == "O")) == 9 and status == "\nKeep Going\n":
            status = "It's a draw"
            print (status)
            break
            
    

 1|2|3 
 4|5|6 
 7|8|9 

X, pick your square
1


 X|2|3 
 4|5|6 
 7|8|9 

Keep Going


O, pick your square
2


 X|O|3 
 4|5|6 
 7|8|9 

Keep Going


X, pick your square
3


 X|O|X 
 4|5|6 
 7|8|9 

Keep Going


O, pick your square
5


 X|O|X 
 4|O|6 
 7|8|9 

Keep Going


X, pick your square
8


 X|O|X 
 4|O|6 
 7|X|9 

Keep Going


O, pick your square
6


 X|O|X 
 4|O|O 
 7|X|9 

Keep Going


X, pick your square
4


 X|O|X 
 X|O|O 
 7|X|9 

Keep Going


O, pick your square
7


 X|O|X 
 X|O|O 
 O|X|9 

Keep Going


X, pick your square
9


 X|O|X 
 X|O|O 
 O|X|X 

Keep Going

It's a draw


In [163]:
import numpy as np
import random
    
tic = np.array([["1","2","3"], ["4","5","6"], ["7","8","9"]])

print ("\033[4m",('|'.join(map(str, tic[0]))),"\033[0m")
print ("\033[4m",('|'.join(map(str, tic[1]))),"\033[0m")
print ("\033[4m",('|'.join(map(str, tic[2]))),"\033[0m")

print ((np.count_nonzero(tic == "1"))+(np.count_nonzero(tic == "2")))

 1|2|3 
 4|5|6 
 7|8|9 
2


In [162]:
print ((np.count_nonzero(tic == "1"))+(np.count_nonzero(tic == "2")))

1
